obj-$(CONFIG_IMX8_MIPI_CSI2_YAV) += mxc-mipi-csi2_yav.o
mxc-jpeg-encdec-objs := mxc-jpeg-hw.o mxc-jpeg.o
obj-$(CONFIG_IMX8_JPEG) += mxc-jpeg-encdec.o
obj-$(CONFIG_MXC_CAMERA_AR0521)   += ar0521.o
obj-$(CONFIG_MXC_CAMERA_AR1335)   += ar1335.o
